### ISSUE TITLE
mime in add.php

### ISSUE THREAD

**Issue by AdamOmega** [boyter/Phindex#1]
Hi,
thanks for your project. However, when trying to run it on my PC I encountered an error: undefinded variable "$mime" in add.php, line 62.
I tried to find out if that variable might be defined on a linux system by default but had no success.
Finally I just replaced the variable by a concrete mime type, i.e. "text/plain". Then it worked, i.e. the index was built.
I am now suggesting to do the same replacement on your code as others might have that problem too.
Or am I missing something? Does this work on a linux system? Or does it depend on the PHP version? Or on the presence of a certain php library?
Thank you
Best regards, Rob

**Comment by boyter** [comment]
Hey @AdamOmega I have not really looked at this in so long. Looking at the code https://github.com/boyter/Phindex/blob/master/add.php#L62 I think you are right though. Feel free to send through the PR and ill merge it in straight away.

**Comment by AdamOmega** [comment]
Hm, maybe I should not have closed the PR, but hopefully you'll be able to do the merge though, if you think that the change is right. Thanks

**Comment by boyter** [comment]
Merged in, and thanks for the submission!
